class METHODTYPE:
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    HEAD = "HEAD"


class STATUSCODE:
    SUCCESS = 200
    BADREQUEST = 400
    UNAUTHORIZED = 401
    FAIL = 500
